[package]
name = "reqsign"
version = "0.0.0"
edition = "2021"
authors = ["Xuanwo <github@xuanwo.io>"]
description = "Signing requests for cloud services"
documentation = "https://docs.rs/reqsign"
license = "Apache-2.0"
categories = ["command-line-utilities", "web-programming"]

[dependencies]
